#ifndef _SOCKET_CLIENT_REGISTRY_H_
#define _SOCKET_CLIENT_REGISTRY_H_

#include "ROOT_SOCKET_CLIENT.h"

#define MAX_ROOT_SOCKETS 5

struct SOCKET_CLIENT_REGISTRY {
	ROOT_SOCKET_CLIENT root_sockets[MAX_ROOT_SOCKETS];
};

bool Initialize_SOCKET_CLIENT_REGISTRY(SOCKET_CLIENT_REGISTRY*);
void Delete_SOCKET_CLIENT_REGISTRY(SOCKET_CLIENT_REGISTRY*);

#endif