//PLATFORMS: Linux, Windows, OSX

#ifndef HERMES_H_
#define HERMES_H_

#include <string>
#include "../Networking/NETWORK.h"
#include "../Utilities/CONCURRENT_QUEUE.h"
#include "../Utilities/UTILS.h"

#define HERMES_CONNECTIONS_MAX MAX_UDP_CONNECTIONS

#define HERMES_PORT_MIN 2230
#define HERMES_PORT_MAX 3329

#define HERMES_NULL		(HERMES_TYPE){"null", NETWORK_TYPE_TCP, 0}
//NETWORK_TYPE_UDP
#define HERMES_AUDIO		(HERMES_TYPE){"audio", NETWORK_TYPE_TCP, 1}
#define HERMES_DEVICE		(HERMES_TYPE){"device", NETWORK_TYPE_UDP, 2}
//NETWORK_TYPE_UDP
#define HERMES_VIDEO		(HERMES_TYPE){"video", NETWORK_TYPE_TCP, 3}
#define HERMES_PRINT		(HERMES_TYPE){"print", NETWORK_TYPE_TCP, 4}
#define HERMES_DATA		(HERMES_TYPE){"data", NETWORK_TYPE_TCP, 5}
#define HERMES_MIC		(HERMES_TYPE){"mic", NETWORK_TYPE_TCP, 6}
#define HERMES_CAM		(HERMES_TYPE){"cam", NETWORK_TYPE_TCP, 7}
#define HERMES_THEMIS		(HERMES_TYPE){"themis", NETWORK_TYPE_TCP, 8}
#define HERMES_VIDEO_INIT	(HERMES_TYPE){"video_init", NETWORK_TYPE_TCP, 9}
//NETWORK_TYPE_UDP
#define HERMES_KEYBOARD		(HERMES_TYPE){"keyboard", NETWORK_TYPE_TCP, 10}
//NETWORK_TYPE_UDP
#define HERMES_MOUSE		(HERMES_TYPE){"mouse", NETWORK_TYPE_TCP, 11}
#define HERMES_CLIPBOARD	(HERMES_TYPE){"clipboard", NETWORK_TYPE_TCP, 12}
#define HERMES_CLIENT_TCP	(HERMES_TYPE){"hermes_client_tcp", NETWORK_TYPE_TCP, 13}
#define HERMES_CLIENT_WS	(HERMES_TYPE){"hermes_client_ws", NETWORK_TYPE_WS, 14}
#define HERMES_SERVER_TCP	(HERMES_TYPE){"hermes_server_tcp", NETWORK_TYPE_TCP, 15}
#define HERMES_SERVER_WS	(HERMES_TYPE){"hermes_server_ws", NETWORK_TYPE_WS, 16}

#define HERMES_THEMIS_WS	(HERMES_TYPE){"themis_ws", NETWORK_TYPE_WS, 17}
#define HERMES_VIDEO_INIT_WS	(HERMES_TYPE){"video_init_ws", NETWORK_TYPE_WS, 18}
#define HERMES_VIDEO_WS		(HERMES_TYPE){"video_ws", NETWORK_TYPE_WS, 19}
#define HERMES_MOUSE_WS		(HERMES_TYPE){"mouse_ws", NETWORK_TYPE_WS, 20}
#define HERMES_KEYBOARD_WS	(HERMES_TYPE){"keyboard_ws", NETWORK_TYPE_WS, 21}
#define HERMES_AUDIO_WS		(HERMES_TYPE){"audio_ws", NETWORK_TYPE_WS, 22}
#define HERMES_CLIPBOARD_WS	(HERMES_TYPE){"clipboard_ws", NETWORK_TYPE_WS, 23}

#define HERMES_GET_CONNECTION	1
#define HERMES_EXIT 		2
#define HERMES_STATUS 		3

#define HERMES_TIMEOUT_TRIES 10

#define HERMES_STATUS_NORMAL 0
#define HERMES_STATUS_UNEXPECTED_DISCONNECT 1
#define HERMES_STATUS_EXPECTED_DISCONNECT 2
#define HERMES_STATUS_DISCONNECTED 3

#define HERMES_CORE_TIMEOUT 5

struct HERMES_TYPE {
	uint8_t name[MAX_NAME_SIZE];
	int32_t type;
	int32_t id;
}  __attribute__((packed));

#endif
